config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, presence: false, length: { maximum: 50 }
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery
  skip_before_action :verify_authenticity_token
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @errors = session[:book_error]
    if@errors == nil
      @errors = []
    end
    session[:book_error] = nil
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = 'You have created book successfully.';
      redirect_to @book
    else
      session[:book_error] = @book.errors.full_messages
      redirect_to books_path
    end
  end  

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    if session[:book_error]
      @errors = session[:book_error]
      session[:book_error] = nil
      render :edit
    else
      #@errors = nil
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
    @errors = []
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to @book
    else
      session[:book_error] = @book.errors.full_messages
      redirect_to @book
    end  
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end  
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  skip_before_action :verify_authenticity_token
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user = current_user
    end
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to current_user
    end  
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to current_user
    else
      render :edit
    end
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', errors: @errors %>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :body, 'Opinion' %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to 'Show', book_path(@book) %> |  <%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', errors: @errors %>
<div class='row'>
  <%= render 'layouts/sidebar', user: @user, book: @book %>
  <div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <% if book.user.profile_image.attached? %>
                <%= image_tag book.user.profile_image, height: '80' %>
              <% else %>
                  <%= image_tag 'default-image.jpg', height: '80' %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book) %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', user: @book.user, book: @book_new %>
  <div class='col-md-8 offset-md-1'>
    <h2>Book detail</h2>
    <table class='table'>
      <tr>
        <td>
          <%= link_to user_path(@book.user) do %>  
            <%= image_tag @book.user.profile_image.attached? ? @book.user.profile_image : 'default-image.jpg', height: '80' %>
            <br>
            <%= @book.user.name %>
          <% end %>  
        </td>
        <td><%= link_to @book.title, book_path(@book) %></td>
        <td><%= @book.body %></td>
        <% if @book.user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
        <td>
          <%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" =>  '本当に消しますか？' , class: 'btn btn-sm btn-danger destroy_book_29499' %>
        </td>
        <% end %>
      </tr>
    </table>
  </div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
      </div>
      <div class="row">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h3><%= errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_url, class: "navbar-brand" do %>
        <span>Bookers</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :get, class:'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_url, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class='col-md-3'>
  <h2>User info</h2>
  <table class='table'>
    <tr>
      <%= image_tag user.profile_image.attached? ? user.profile_image : 'default-image.jpg', height: '100' %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th>
        <%= user.introduction %>
      </th>
    </tr>
  </table>
  <div class='row'>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <%= f.label :body, 'Opinion' %>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p id="notice">
        <% flash.each do |key, value| %>
          <%= value %>
        <% end %>
      </p>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, 'Image' %>
          <%= f.file_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>  
</div>

app/views/users/index.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', user: @user, book: @book %>
  <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.profile_image.attached? ? user.profile_image : 'default-image.jpg', height: '80' %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', user: @user, book: @book %>
  <div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= image_tag @user.profile_image.attached? ? @user.profile_image : 'default-image.jpg', height: '80' %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book) %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>  